(() => {
    'use strict';
    const API='api/sbo-attendance.php';let csrf='',assignments=[],selected=null,stream=null,detecting=false,lastCode='';
    const selector=document.querySelector('[data-assignment-selector]'),summary=document.querySelector('[data-assignment-summary]'),recent=document.querySelector('[data-recent-scans]'),video=document.querySelector('[data-scanner-video]'),cameraButton=document.querySelector('[data-camera-toggle]');
    const esc=value=>window.SboPortal.escapeHtml(value);const notify=(type,message)=>window.Notifications?.[type]?.(message);
    const formatTime=value=>value?new Intl.DateTimeFormat('en-PH',{hour:'numeric',minute:'2-digit'}).format(new Date(`2000-01-01T${value}`)):'—';
    const renderAssignment=()=>{if(!selected)return;summary.innerHTML=[['Event',selected.event_name],['Day & date',`Day ${selected.day_number} · ${new Intl.DateTimeFormat('en-PH',{dateStyle:'medium'}).format(new Date(`${selected.schedule_date}T00:00:00`))}`],['Session',`${selected.session_name} · ${formatTime(selected.session_start)}–${formatTime(selected.session_end)}`],['Activity & team',`${selected.activity_name} · ${selected.team_name}`]].map(([label,value])=>`<article><span class="text-[10px] font-black uppercase tracking-wider text-[#397565]">${label}</span><strong class="mt-1 block text-sm">${esc(value)}</strong></article>`).join('');document.querySelector('[data-session-state]').textContent=selected.is_session_active?'Session is active — scanning is enabled.':'Session is inactive — scanning is locked.';cameraButton.disabled=!selected.is_session_active;};
    const renderRecent=rows=>{recent.innerHTML=rows.length?rows.map(row=>`<article class="flex items-center gap-3 p-4"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#C6F24E]/35 text-xs font-black text-[#397565]">✓</span><div class="min-w-0"><strong class="block truncate text-sm">${esc(row.full_name)}</strong><span class="block text-xs text-[#121017]/45">${esc(row.id_number)} · ${esc(row.year_level||'Student')}</span></div><time class="ml-auto shrink-0 text-[10px] font-bold text-[#397565]">${new Intl.DateTimeFormat('en-PH',{hour:'numeric',minute:'2-digit'}).format(new Date(row.scanned_at.replace(' ','T')))}</time></article>`).join(''):'<div class="p-8 text-center text-sm text-[#121017]/45">No attendance scans yet.</div>';};
    const load=async id=>{const response=await axios.get(API,{params:id?{assignment_id:id}:{}});const data=response.data.data;assignments=data.assignments;if(!id){document.querySelector('[data-no-assignment]').classList.toggle('hidden',assignments.length>0);document.querySelector('[data-attendance-workspace]').classList.toggle('hidden',assignments.length===0);selector.innerHTML=assignments.map(item=>`<option value="${item.id}">${esc(item.event_name)} · ${esc(item.activity_name)} · ${esc(item.team_name)}</option>`).join('');document.querySelector('[data-assignment-selector-wrap]').classList.toggle('hidden',assignments.length<2);document.querySelector('[data-assignment-selector-wrap]').classList.toggle('grid',assignments.length>1);}selected=data.selected_assignment||(id?assignments.find(item=>item.id===Number(id)):assignments[0]);if(selected){selector.value=selected.id;renderAssignment();renderRecent(data.recent_scans);}};
    const submit=async payload=>{try{const response=await axios.post(API,{...payload,assignment_id:selected.id},{headers:{'X-CSRF-Token':csrf}});notify('success',response.data.message);renderRecent(response.data.recent_scans);return true;}catch(error){notify(error.response?.status===409?'warning':'error',error.response?.data?.message||'Attendance scan failed.');return false;}};
    const stop=()=>{detecting=false;stream?.getTracks().forEach(track=>track.stop());stream=null;video.srcObject=null;cameraButton.textContent='Start camera';};
    const loop=async detector=>{if(!detecting)return;try{const codes=await detector.detect(video);const code=codes[0]?.rawValue;if(code&&code!==lastCode){lastCode=code;await submit({mode:'qr',code});setTimeout(()=>lastCode='',2500);}}catch{}requestAnimationFrame(()=>loop(detector));};
    cameraButton.addEventListener('click',async()=>{if(stream){stop();return;}if(!selected?.is_session_active)return;if(!('BarcodeDetector'in window)){notify('warning','QR scanning is not supported by this browser. Use Student ID entry.');return;}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});video.srcObject=stream;await video.play();cameraButton.textContent='Stop camera';document.querySelector('[data-camera-message]').textContent='Point the student QR code inside the frame.';detecting=true;loop(new BarcodeDetector({formats:['qr_code']}));}catch{notify('error','Camera is unavailable. Use Student ID entry instead.');stop();}});
    selector.addEventListener('change',()=>{stop();load(Number(selector.value));});
    document.querySelector('[data-manual-form]').addEventListener('submit',async event=>{event.preventDefault();if(!selected?.is_session_active){notify('warning','Inactive session. Scanning is locked.');return;}const input=event.currentTarget.elements.student_id;if(await submit({mode:'manual',student_id:input.value}))event.currentTarget.reset();});
    window.addEventListener('beforeunload',stop);
    SboPortal.initialize('attendance').then(context=>{csrf=context.csrfToken;return load();}).catch(error=>notify('error',error.response?.data?.message||error.message));
})();
