@extends('layouts.student')
@section('title','Home')
@section('content')
<div class="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_340px]">
<div class="min-w-0 space-y-5">
    <section class="rounded-3xl border border-[#121017]/8 bg-white p-5 shadow-[0_12px_35px_rgba(18,16,23,.05)]">
        <div class="flex gap-3"><x-student-avatar :user="$user"/><div><h1 class="text-lg font-black">Share with CITE</h1><p class="text-xs text-[#121017]/45">Posts are reviewed by an SBO Adviser before everyone can see them.</p></div></div>
        <form class="mt-4" method="POST" action="{{ route('student.posts.store') }}" enctype="multipart/form-data" data-submit-form>@csrf
            <label class="sr-only" for="post-content">Post caption</label><textarea class="min-h-28 w-full resize-y rounded-2xl border border-[#121017]/10 bg-[#F7F4ED]/70 p-4 text-sm outline-none placeholder:text-[#121017]/35 focus:border-[#397565]/50 focus:bg-white focus:ring-4 focus:ring-[#397565]/8" id="post-content" name="content" placeholder="What would you like the CITE community to know?" required maxlength="3000">{{ old('content') }}</textarea>
            <div class="mt-3 grid gap-3 sm:grid-cols-2"><label><span class="mb-1.5 block text-[10px] font-black uppercase tracking-wider text-[#121017]/45">Event</span><select class="h-11 w-full rounded-xl border border-[#121017]/10 bg-white px-3 text-xs font-bold" name="event_id"><option value="">General community</option>@foreach($events as $event)<option value="{{ $event->id }}" @selected(old('event_id')==$event->id)>{{ $event->title }}</option>@endforeach</select></label><label><span class="mb-1.5 block text-[10px] font-black uppercase tracking-wider text-[#121017]/45">Category</span><select class="h-11 w-full rounded-xl border border-[#121017]/10 bg-white px-3 text-xs font-bold" name="category" required>@foreach(\App\Models\Post::CATEGORIES as $category)<option value="{{ $category }}" @selected(old('category')===$category)>{{ str($category)->replace('-',' ')->title() }}</option>@endforeach</select></label></div>
            <div class="mt-4 flex flex-wrap items-center gap-3"><label class="inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-xl border border-[#121017]/10 px-4 text-xs font-black text-[#397565] hover:bg-[#397565]/7"><svg class="h-4 w-4 fill-none stroke-current stroke-2" viewBox="0 0 24 24"><path d="M4 16l4-4 4 4 3-3 5 5M4 5h16v14H4V5Z"/></svg>Add image<input class="sr-only" type="file" name="image" accept="image/jpeg,image/png,image/webp" data-image-input></label><span class="min-w-0 flex-1 truncate text-xs text-[#121017]/40" data-file-name>JPG, PNG or WebP · up to 5 MB</span><button class="min-h-11 rounded-xl bg-[#397565] px-6 text-xs font-black text-white shadow-lg shadow-[#397565]/15 hover:bg-[#2f6658] disabled:opacity-50" type="submit" data-loading-text="Submitting…">Submit post</button></div>
        </form>
        @if($errors->any())<div class="mt-4 rounded-xl bg-[#FF6B2C]/9 px-4 py-3 text-xs font-bold text-[#c84510]" role="alert">{{ $errors->first() }}</div>@endif
    </section>

    <div class="flex items-end justify-between"><div><p class="text-[10px] font-black uppercase tracking-[.15em] text-[#397565]">Community feed</p><h2 class="mt-1 text-2xl font-black tracking-tight">What’s happening</h2></div><span class="text-xs text-[#121017]/40">Approved posts only</span></div>
    @forelse($posts as $post)<article class="overflow-hidden rounded-3xl border border-[#121017]/8 bg-white shadow-[0_12px_35px_rgba(18,16,23,.045)]"><header class="flex items-center gap-3 p-5"><x-student-avatar :user="$post->author"/><div class="min-w-0 flex-1"><strong class="block truncate text-sm">{{ $post->author->full_name }}</strong><div class="flex flex-wrap items-center gap-1.5 text-[10px] text-[#121017]/40"><time datetime="{{ $post->reviewed_at?->toIso8601String() }}">{{ $post->reviewed_at?->diffForHumans() }}</time><span>·</span><span class="font-bold text-[#397565]">{{ str($post->category)->replace('-',' ')->title() }}</span>@if($post->event)<span>· {{ $post->event->title }}</span>@endif</div></div>@if($post->user_id===$user->id)<span class="rounded-full bg-[#397565]/8 px-2 py-1 text-[9px] font-black text-[#397565]">Yours</span>@endif</header><div class="px-5 pb-5"><p class="whitespace-pre-line text-sm leading-6">{{ $post->content }}</p></div>@if($post->image_path)<img class="max-h-[620px] w-full border-t border-[#121017]/7 bg-[#F7F4ED] object-contain" src="{{ asset('storage/'.$post->image_path) }}" alt="Image attached to {{ $post->author->full_name }}'s post" loading="lazy">@endif
    @if($post->user_id===$user->id)<details class="border-t border-[#121017]/7 p-4"><summary class="inline-flex min-h-10 cursor-pointer items-center rounded-xl px-3 text-xs font-black text-[#397565] hover:bg-[#397565]/7">Edit approved post</summary><form class="mt-3 grid gap-3 rounded-2xl bg-[#F7F4ED]/70 p-4" method="POST" action="{{ route('student.posts.update',$post) }}" enctype="multipart/form-data">@csrf @method('PUT')<p class="text-[10px] font-bold text-[#FF6B2C]">Saving changes returns this post to Pending for adviser review.</p><textarea class="min-h-24 rounded-xl border border-[#121017]/10 bg-white p-3 text-sm" name="content" required>{{ $post->content }}</textarea><div class="grid gap-2 sm:grid-cols-2"><select class="h-10 rounded-xl border border-[#121017]/10 bg-white px-3 text-xs" name="event_id"><option value="">General community</option>@foreach($events as $event)<option value="{{ $event->id }}" @selected($post->event_id===$event->id)>{{ $event->title }}</option>@endforeach</select><select class="h-10 rounded-xl border border-[#121017]/10 bg-white px-3 text-xs" name="category">@foreach(\App\Models\Post::CATEGORIES as $category)<option value="{{ $category }}" @selected($post->category===$category)>{{ str($category)->replace('-',' ')->title() }}</option>@endforeach</select></div><input class="text-xs" type="file" name="image" accept="image/jpeg,image/png,image/webp"><button class="min-h-10 rounded-xl bg-[#397565] px-4 text-xs font-black text-white">Save and resubmit</button></form></details>@endif</article>
    @empty<div class="rounded-3xl border border-dashed border-[#397565]/25 bg-white px-6 py-16 text-center"><span class="text-3xl" aria-hidden="true">🌿</span><h3 class="mt-3 font-black">The feed is ready for its first story</h3><p class="mt-1 text-sm text-[#121017]/45">Approved student posts will appear here.</p></div>@endforelse
    @if($posts->hasPages())<div>{{ $posts->links() }}</div>@endif
</div>

<aside class="space-y-5 lg:sticky lg:top-24">
    @if($myPosts->isNotEmpty())
    <section class="rounded-3xl border border-[#397565]/15 bg-[#397565]/8 p-5 shadow-[0_12px_35px_rgba(18,16,23,.05)]">
        <div class="flex items-start gap-3"><span class="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-[#397565] text-white"><svg class="h-5 w-5 fill-none stroke-current stroke-2" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 4h14v16H5V4Zm3 4h8m-8 4h8m-8 4h5"/></svg></span><div class="min-w-0 flex-1"><div class="flex items-center justify-between gap-2"><h2 class="font-black">Your submissions</h2><span class="rounded-full bg-[#C6F24E] px-2.5 py-1 text-[10px] font-black text-[#121017]">{{ $myPosts->count() }}</span></div><p class="mt-1 text-xs leading-5 text-[#121017]/50">{{ $myPosts->where('status','pending')->count() }} waiting · {{ $myPosts->where('status','rejected')->count() }} rejected</p></div></div>
        <button class="mt-4 flex min-h-11 w-full items-center justify-center rounded-xl bg-white text-xs font-black text-[#397565] shadow-sm hover:bg-[#F7F4ED]" type="button" data-submissions-open>View pending posts</button>
    </section>
    @endif
    @if($currentEvent)<section class="overflow-hidden rounded-3xl border border-[#121017]/8 bg-white shadow-[0_12px_35px_rgba(18,16,23,.05)]">@if($currentEvent->poster_path)<img class="h-40 w-full object-cover" src="{{ asset('storage/'.$currentEvent->poster_path) }}" alt="{{ $currentEvent->title }} poster">@else<div class="grid h-28 place-items-center bg-gradient-to-br from-[#397565] to-[#234f44] text-5xl font-black text-white/20">CITE</div>@endif<div class="p-5"><div class="flex items-center justify-between gap-2"><span class="text-[9px] font-black uppercase tracking-wider text-[#397565]">Current event</span><span class="rounded-full bg-[#C6F24E]/35 px-2.5 py-1 text-[9px] font-black uppercase text-[#397565]">{{ $currentEvent->schedule_state==='ongoing'?'Live':($currentEvent->schedule_state==='completed'?'Finished':'Upcoming') }}</span></div><h2 class="mt-2 text-xl font-black">{{ $currentEvent->title }}</h2><p class="mt-2 text-xs leading-5 text-[#121017]/50">{{ $currentEvent->start_at->format('M j, Y · g:i A') }}<br>{{ $currentEvent->location ?: 'CITE Campus' }}</p><div class="mt-4 rounded-xl bg-[#F7F4ED] p-3"><span class="text-[9px] font-black uppercase text-[#121017]/40">Your tribe</span><strong class="mt-1 block text-sm">{{ $user->teams->pluck('name')->join(', ') ?: 'Not assigned' }}</strong></div></div></section>
    <section class="rounded-3xl border border-[#121017]/8 bg-white p-5"><div class="flex items-center justify-between"><h2 class="font-black">Leaderboard</h2><span class="text-[10px] text-[#121017]/40">Overall</span></div><ol class="mt-4 space-y-2">@foreach($leaderboard as $team)<li class="flex items-center gap-3 rounded-xl bg-[#F7F4ED]/70 p-3"><span class="grid h-7 w-7 place-items-center rounded-lg bg-white text-xs font-black">{{ $team->rank }}</span><i class="h-3 w-3 rounded-full" style="background:{{ $team->color }}"></i><strong class="min-w-0 flex-1 truncate text-xs">{{ $team->name }}</strong><span class="text-xs font-black text-[#397565]">{{ number_format($team->total_score,1) }}</span></li>@endforeach</ol><a class="mt-4 flex min-h-11 items-center justify-center rounded-xl border border-[#397565]/20 text-xs font-black text-[#397565] hover:bg-[#397565]/7" href="{{ route('student.leaderboard.index') }}">View Full Leaderboard</a></section>
    @if($announcements->isNotEmpty())<section class="rounded-3xl border border-[#121017]/8 bg-white p-5"><h2 class="font-black">Event announcements</h2><div class="mt-3 space-y-3">@foreach($announcements as $item)<div class="border-l-2 border-[#397565] pl-3"><p class="line-clamp-3 text-xs leading-5">{{ $item->content }}</p><span class="mt-1 block text-[9px] text-[#121017]/40">{{ $item->author->full_name }}</span></div>@endforeach</div></section>@endif
    @else<div class="rounded-3xl border border-dashed border-[#397565]/25 bg-white p-6"><h2 class="font-black">No active event</h2><p class="mt-2 text-xs leading-5 text-[#121017]/45">Your next assigned event will appear here when it is scheduled.</p></div>@endif
</aside></div>

@if($myPosts->isNotEmpty())
<dialog class="m-auto max-h-[calc(100vh_-_2rem)] w-[min(760px,calc(100%_-_2rem))] overflow-hidden rounded-3xl border-0 bg-white p-0 text-[#121017] shadow-[0_28px_90px_rgba(18,16,23,.3)] backdrop:bg-[#0d1714]/75 backdrop:backdrop-blur-sm dark:bg-[#17231f] dark:text-[#eef5f2]" data-submissions-dialog aria-labelledby="submissions-title">
    <header class="flex items-start justify-between gap-4 border-b border-[#121017]/8 p-5 sm:p-6"><div><div class="flex items-center gap-2"><h2 class="text-xl font-black" id="submissions-title">Your submissions</h2><span class="rounded-full bg-[#C6F24E] px-2.5 py-1 text-[10px] font-black text-[#121017]">{{ $myPosts->count() }}</span></div><p class="mt-1 text-xs text-[#121017]/45">Only you can see these review updates.</p></div><button class="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#F7F4ED] text-xl hover:bg-[#397565]/10" type="button" data-submissions-close aria-label="Close submissions">&times;</button></header>
    <div class="max-h-[calc(100vh_-_9rem)] space-y-3 overflow-y-auto p-5 sm:p-6">
        @foreach($myPosts as $post)
        <article class="rounded-2xl border p-4 {{ $post->status==='rejected'?'border-[#FF6B2C]/25 bg-[#FF6B2C]/5':'border-[#397565]/15 bg-[#397565]/5' }}">
            <div class="flex items-center justify-between gap-3"><span class="rounded-full px-2.5 py-1 text-[9px] font-black uppercase {{ $post->status==='rejected'?'bg-[#FF6B2C]/15 text-[#c84510]':'bg-[#C6F24E]/35 text-[#397565]' }}">{{ $post->status==='pending'?'Waiting for adviser approval':'Rejected' }}</span><time class="text-[10px] text-[#121017]/40">{{ $post->created_at->diffForHumans() }}</time></div>
            <p class="mt-3 whitespace-pre-line text-sm leading-6">{{ $post->content }}</p>
            @if($post->image_path)<img class="mt-3 max-h-56 w-full rounded-xl object-cover" src="{{ asset('storage/'.$post->image_path) }}" alt="Post attachment">@endif
            @if($post->rejection_reason)<p class="mt-3 rounded-xl bg-white px-3 py-2 text-xs"><strong>Adviser note:</strong> {{ $post->rejection_reason }}</p>@endif
            @if($post->status==='pending')
            <div class="mt-3 flex items-start gap-2"><details class="min-w-0 flex-1"><summary class="inline-flex min-h-10 cursor-pointer items-center rounded-xl border border-[#121017]/10 bg-white px-4 text-xs font-black">Edit</summary><form class="mt-3 grid gap-3 rounded-xl bg-white p-3" method="POST" action="{{ route('student.posts.update',$post) }}" enctype="multipart/form-data">@csrf @method('PUT')<textarea class="min-h-24 rounded-xl border border-[#121017]/10 p-3 text-sm" name="content" required>{{ $post->content }}</textarea><div class="grid gap-2 sm:grid-cols-2"><select class="h-10 rounded-xl border border-[#121017]/10 px-3 text-xs" name="event_id"><option value="">General community</option>@foreach($events as $event)<option value="{{ $event->id }}" @selected($post->event_id===$event->id)>{{ $event->title }}</option>@endforeach</select><select class="h-10 rounded-xl border border-[#121017]/10 px-3 text-xs" name="category">@foreach(\App\Models\Post::CATEGORIES as $category)<option value="{{ $category }}" @selected($post->category===$category)>{{ str($category)->replace('-',' ')->title() }}</option>@endforeach</select></div><input class="text-xs" type="file" name="image" accept="image/jpeg,image/png,image/webp"><button class="min-h-10 rounded-xl bg-[#397565] px-4 text-xs font-black text-white">Save changes</button></form></details><form method="POST" action="{{ route('student.posts.destroy',$post) }}" onsubmit="return confirm('Delete this pending post?')">@csrf @method('DELETE')<button class="min-h-10 rounded-xl border border-[#FF6B2C]/25 bg-white px-4 text-xs font-black text-[#c84510]">Delete</button></form></div>
            @endif
        </article>
        @endforeach
    </div>
</dialog>
@endif
@endsection
