(() => {
  'use strict';
  const page = document.body.dataset.facultyPage;
  const host = document.querySelector('[data-faculty-content]');
  const esc = value => window.SharedNavigation.escapeHtml(value);
  const card = (body, extra='') => `<section class="rounded-3xl border border-[#397565]/15 bg-white p-5 shadow-sm sm:p-6 ${extra}">${body}</section>`;
  const empty = message => card(`<p class="py-10 text-center text-sm text-[#121017]/55">${esc(message)}</p>`);
  const date = value => value ? new Date(value.replace(' ','T')).toLocaleString('en-PH',{dateStyle:'medium',timeStyle:'short'}) : '—';
  const status = value => `<span class="rounded-full bg-[#397565]/10 px-2 py-1 text-xs font-bold text-[#397565]">${esc(value || 'Unrecorded')}</span>`;
  const get = async (name=page, params={}) => (await axios.get('api/faculty.php',{params:{page:name,...params}})).data.data;
  let csrf = '';

  async function students() {
    const data=await get();
    if (!data.team) { host.innerHTML=empty('No team is assigned to your Faculty account. Contact the SBO Adviser.'); return; }
    host.innerHTML=card(`<div class="flex flex-wrap gap-3"><input class="min-h-11 flex-1 rounded-xl border px-3" placeholder="Search name or Student ID" data-search aria-label="Search students"><select class="min-h-11 rounded-xl border px-3" data-event aria-label="Filter event"><option value="">All events</option>${Object.entries(data.events).map(([id,title])=>`<option value="${id}">${esc(title)}</option>`).join('')}</select><select class="min-h-11 rounded-xl border px-3" data-status aria-label="Filter attendance status"><option value="">All statuses</option>${['present','late','absent','excused','unrecorded'].map(s=>`<option>${s}</option>`).join('')}</select></div><p class="mt-3 text-xs text-[#121017]/50">${esc(data.team.name)} · View only</p><div class="mt-5 grid gap-3" data-list></div>`);
    const render=()=>{
      const q=host.querySelector('[data-search]').value.toLowerCase(), event=host.querySelector('[data-event]').value, filter=host.querySelector('[data-status]').value;
      const visible=data.students.filter(s=>{
        const records=s.attendance.filter(a=>!event || String(a.event_id)===event);
        return (`${s.name} ${s.id_number}`).toLowerCase().includes(q) && (!filter || (filter==='unrecorded' ? !records.length : records.some(a=>a.status===filter)));
      });
      host.querySelector('[data-list]').innerHTML=visible.length ? visible.map(s=>{
        const records=s.attendance.filter(a=>!event || String(a.event_id)===event);
        return `<details class="rounded-2xl border border-[#121017]/10 p-4"><summary class="cursor-pointer font-bold">${esc(s.name)} <span class="ml-2 text-xs font-normal text-[#121017]/50">${esc(s.id_number)} · ${esc(s.year_level || 'Year not set')} · ${esc(s.team)} · ${records.length} attendance records</span></summary><div class="mt-3 grid gap-2">${records.length ? records.map(a=>`<div class="rounded-xl bg-[#F7F4ED] p-3 text-sm"><strong>${esc(a.event_title)}</strong> · ${esc(a.date)} ${status(a.status)}<p class="mt-2 text-xs text-[#121017]/55">Morning: ${esc(a.morning_in_at || '—')} – ${esc(a.morning_out_at || '—')} · Afternoon: ${esc(a.afternoon_in_at || '—')} – ${esc(a.afternoon_out_at || '—')}</p></div>`).join('') : '<p class="text-sm text-[#121017]/50">No attendance recorded.</p>'}</div></details>`;
      }).join('') : '<p class="py-8 text-center text-sm text-[#121017]/50">No matching students.</p>';
    };
    host.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',render)); render();
  }

  async function leaderboard() {
    const first=await get(); let selected=first.events.find(e=>new Date(e.end_at.replace(' ','T'))>=new Date())?.id || first.events[0]?.id || null;
    let category=''; let past=false;
    const render=async()=>{
      const data=await get('leaderboard',selected?{event_id:selected,...(category?{category_id:category}:{})}:{});
      const now=new Date(); const active=first.events.filter(e=>new Date(e.end_at.replace(' ','T'))>=now), old=first.events.filter(e=>new Date(e.end_at.replace(' ','T'))<now);
      host.innerHTML=`<div class="flex flex-wrap gap-2">${active.map(e=>`<button class="rounded-xl px-4 py-2 text-sm font-bold ${selected==e.id?'bg-[#397565] text-white':'bg-white text-[#397565]'}" data-event="${e.id}">${esc(e.title)}</button>`).join('')}<button class="rounded-xl px-4 py-2 text-sm font-bold ${past?'bg-[#397565] text-white':'bg-white text-[#397565]'}" data-past>Past Events</button></div>${past?`<div class="mt-3 flex flex-wrap gap-2">${old.map(e=>`<button class="rounded-xl border px-3 py-2 text-xs font-bold ${selected==e.id?'border-[#397565] text-[#397565]':''}" data-event="${e.id}">${esc(e.title)}</button>`).join('') || '<p class="text-sm">No past events.</p>'}</div>`:''}<div class="mt-5"><label class="text-sm font-bold">Category <select class="ml-2 min-h-11 rounded-xl border bg-white px-3" data-category><option value="">All categories</option>${data.categories.map(c=>`<option value="${c.id}" ${category==c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label></div><div class="mt-5 grid gap-3">${data.rankings.length?data.rankings.map(t=>card(`<div class="flex items-center justify-between gap-3"><div><span class="text-xs font-bold text-[#397565]">#${t.rank || '—'}</span><h2 class="font-black">${esc(t.name)} ${t.id===data.team_id?'<span class="rounded-full bg-[#C6F24E] px-2 py-1 text-xs">Your team</span>':''}</h2></div><strong class="text-xl">${t.total_score} pts</strong></div>`,t.id===data.team_id?'ring-2 ring-[#397565]':'')).join(''):empty('No scores are available for this event and category.')}</div>`;
      host.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.event);category='';render();});
      host.querySelector('[data-past]').onclick=()=>{past=!past;render();};
      host.querySelector('[data-category]').onchange=e=>{category=e.target.value;render();};
    }; await render();
  }

  async function team() {
    const {team:t}=await get();
    if (!t) {host.innerHTML=empty('No team is assigned to your Faculty account. Contact the SBO Adviser.');return;}
    host.innerHTML=`<div class="grid gap-4 md:grid-cols-3">${card(`<p class="text-xs uppercase text-[#397565]">Assigned team</p><h2 class="mt-2 text-2xl font-black">${esc(t.name)}</h2><p class="text-sm">${esc(t.school_year)}</p>`)}${card(`<p class="text-xs uppercase text-[#397565]">Current rank</p><strong class="text-3xl">${t.rank?'#'+t.rank:'Unranked'}</strong>`)}${card(`<p class="text-xs uppercase text-[#397565]">Members</p><strong class="text-3xl">${t.members.length}</strong>`)}</div><div class="mt-4 grid gap-4 md:grid-cols-2">${card(`<h2 class="font-black">Members</h2><ul class="mt-3 space-y-2 text-sm">${t.members.map(m=>`<li>${esc(m.name)} · ${esc(m.id_number)}</li>`).join('') || '<li>No members yet.</li>'}</ul>`)}${card(`<h2 class="font-black">Scores</h2><ul class="mt-3 space-y-2 text-sm">${t.scores.map(s=>`<li>${esc(s.event_title)} · ${esc(s.category)}: <strong>${s.points} pts</strong></li>`).join('') || '<li>No scores yet.</li>'}</ul>`)}${card(`<h2 class="font-black">Attendance summary</h2><ul class="mt-3 space-y-2 text-sm">${t.attendance.map(a=>`<li>${esc(a.status)}: ${a.total}</li>`).join('') || '<li>No attendance yet.</li>'}</ul>`)}${card(`<h2 class="font-black">Upcoming activities</h2><ul class="mt-3 space-y-2 text-sm">${t.activities.map(a=>`<li>${esc(a.title)} · ${date(a.start_at)}</li>`).join('') || '<li>No upcoming activities.</li>'}</ul>`)}${card(`<h2 class="font-black">Announcements</h2><ul class="mt-3 space-y-3 text-sm">${t.announcements.map(a=>`<li>${esc(a.content)} <span class="text-xs text-[#121017]/45">${date(a.created_at)}</span></li>`).join('') || '<li>No announcements.</li>'}</ul>`,'md:col-span-2')}</div>`;
  }

  async function attendance() {
    const data=await get();
    if(!data.team){host.innerHTML=empty('No team is assigned to your Faculty account. Contact the SBO Adviser before scanning attendance.');return;}
    host.innerHTML=card(`<h2 class="font-black">Scan student attendance</h2><p class="mt-1 text-sm text-[#121017]/55">Only Student QR codes from ${esc(data.team.name)} can be recorded. Choose the event session and Time In or Time Out.</p><label class="mt-4 grid gap-1 text-sm font-bold">Event session<select class="min-h-11 rounded-xl border bg-white px-3" data-scan-session></select></label><div class="mt-4 flex gap-2"><button class="min-h-11 rounded-xl border px-4 text-sm font-bold" type="button" data-phase="in">Time In</button><button class="min-h-11 rounded-xl border px-4 text-sm font-bold" type="button" data-phase="out">Time Out</button></div><p class="mt-3 text-sm text-[#121017]/55" data-scan-window></p><button class="mt-4 min-h-11 rounded-xl bg-[#397565] px-5 text-sm font-bold text-white disabled:opacity-40" type="button" data-camera-button>Open QR scanner</button><div class="mt-4 hidden max-w-lg overflow-hidden rounded-xl bg-[#121017]" data-camera-panel><video class="aspect-square w-full object-cover" playsinline muted data-camera-video></video></div><p class="mt-3 text-sm" data-scan-message aria-live="polite">Ready to scan.</p>`)+card('<h2 class="font-black">Your team scans</h2><div class="mt-3 grid gap-2" data-scan-history></div>','mt-4');
    let sessions=data.sessions||[],phase='in',scanner=null,qrModule=null,working=false,lastToken='',lastAt=0;
    const select=host.querySelector('[data-scan-session]'),video=host.querySelector('[data-camera-video]'),cameraButton=host.querySelector('[data-camera-button]'),panel=host.querySelector('[data-camera-panel]'),message=host.querySelector('[data-scan-message]');
    const selected=()=>sessions.find(s=>`${s.event_schedule_id}:${s.session_code}`===select.value);
    const history=records=>{host.querySelector('[data-scan-history]').innerHTML=records.length?records.map(r=>`<div class="rounded-xl border border-[#121017]/10 p-3 text-sm"><strong>${esc(r.student_name)}</strong> · ${esc(r.id_number)}<p class="mt-1 text-xs text-[#121017]/55">${esc(r.event_title)} · ${esc(r.phase==='out'?'Time Out':'Time In')} · ${date(r.scanned_at)}</p></div>`).join(''):'<p class="text-sm text-[#121017]/50">No students scanned yet.</p>';};
    const stop=()=>{if(scanner){scanner.destroy();scanner=null;}panel.classList.add('hidden');cameraButton.textContent='Open QR scanner';};
    const controls=()=>{const s=selected();host.querySelectorAll('[data-phase]').forEach(b=>{const active=b.dataset.phase===phase;b.classList.toggle('bg-[#397565]',active);b.classList.toggle('text-white',active);b.classList.toggle('bg-white',!active);});const open=Boolean(s?.[`${phase}_window_open`]);cameraButton.disabled=!open;host.querySelector('[data-scan-window]').textContent=!s?'No attendance session is enabled for your team today.':open?`Time ${phase==='in'?'In':'Out'} scanning is open for ${s.event_name}.`:`Time ${phase==='in'?'In':'Out'} scanning is closed for ${s.event_name}.`;if(!open)stop();};
    const refresh=async()=>{const updated=await get('attendance');sessions=updated.sessions||[];const value=select.value;select.innerHTML=sessions.map(s=>`<option value="${s.event_schedule_id}:${s.session_code}">${esc(s.event_name)} · ${esc(s.session_name)}</option>`).join('');if(sessions.some(s=>`${s.event_schedule_id}:${s.session_code}`===value))select.value=value;history(updated.records||[]);controls();};
    const location=()=>new Promise(resolve=>{if(!navigator.geolocation){resolve({unavailable_reason:'geolocation_unavailable'});return;}navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_m:p.coords.accuracy,timestamp_ms:p.timestamp}),e=>resolve({unavailable_reason:e.code===1?'permission_denied':e.code===3?'location_timeout':'location_unavailable'}),{enableHighAccuracy:true,maximumAge:5000,timeout:8000});});
    const scan=async result=>{const token=String(result?.data||'').trim(),s=selected();if(!token||!s||working||!s[`${phase}_window_open`]||(token===lastToken&&Date.now()-lastAt<30000))return;working=true;lastToken=token;lastAt=Date.now();message.textContent='Checking location and recording attendance…';try{const response=await axios.post('api/faculty.php?page=scan',{schedule_id:s.event_schedule_id,session:s.session_code,checkpoint:phase,mode:'qr',token,location:await location()},{headers:{'X-CSRF-Token':csrf}});const student=response.data.data.student;message.textContent=`${phase==='in'?'Time In':'Time Out'} recorded for ${student.full_name} (${student.id_number}).`;message.className='mt-3 text-sm font-bold text-[#397565]';await refresh();}catch(e){message.textContent=e.response?.data?.message||'Attendance scan failed.';message.className='mt-3 text-sm font-bold text-[#D64A12]';lastAt=Date.now()-29000;}finally{working=false;}};
    cameraButton.onclick=async()=>{if(scanner){stop();return;}if(!window.isSecureContext){message.textContent='Camera scanning requires HTTPS or localhost.';return;}try{qrModule??=(await import(new URL('js/vendor/qr-scanner/qr-scanner.min.js',document.baseURI))).default;scanner=new qrModule(video,scan,{preferredCamera:'environment',maxScansPerSecond:10,highlightScanRegion:true,highlightCodeOutline:true,returnDetailedScanResult:true});panel.classList.remove('hidden');await scanner.start();cameraButton.textContent='Close scanner';message.textContent='Point the camera at a student QR code.';}catch(e){stop();message.textContent=e?.message||'Camera is unavailable. Check permission and retry.';}};
    host.querySelectorAll('[data-phase]').forEach(b=>b.onclick=()=>{phase=b.dataset.phase;controls();});select.onchange=()=>{stop();controls();};history(data.records||[]);if(sessions.some(s=>s.in_window_open))phase='in';else if(sessions.some(s=>s.out_window_open))phase='out';select.innerHTML=sessions.map(s=>`<option value="${s.event_schedule_id}:${s.session_code}">${esc(s.event_name)} · ${esc(s.session_name)}</option>`).join('');controls();
    const timer=setInterval(()=>{if(!document.hidden&&!working)refresh().catch(()=>{});},30000);window.addEventListener('pagehide',()=>{clearInterval(timer);stop();},{once:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
  }

  async function posts() {
    const data=await get(); let past=false;
    const render=()=>{
      host.innerHTML=card(`<h2 class="font-black">Create a post</h2><form class="mt-4 grid gap-3" data-post-form><select class="min-h-11 rounded-xl border px-3" name="event_id"><option value="">General post</option>${data.events.map(e=>`<option value="${e.id}">${esc(e.title)}</option>`).join('')}</select><textarea class="min-h-28 rounded-xl border p-3" name="content" maxlength="3000" placeholder="Share an update" required></textarea><input type="file" name="image" accept="image/jpeg,image/png,image/webp"><button class="w-fit rounded-xl bg-[#397565] px-5 py-3 text-sm font-bold text-white">Publish</button></form>`)+`<div class="mt-5 flex gap-2"><button class="rounded-xl px-4 py-2 ${!past?'bg-[#397565] text-white':'bg-white'}" data-filter="all">All Posts</button><button class="rounded-xl px-4 py-2 ${past?'bg-[#397565] text-white':'bg-white'}" data-filter="past">Past Events</button></div><div class="mt-4 grid gap-3">${data.posts.filter(p=>!past || (p.end_at && new Date(p.end_at.replace(' ','T'))<new Date())).map(p=>card(`<div class="flex items-center justify-between"><strong>${esc(p.first_name)} ${esc(p.last_name)} ${p.author_role==='Faculty'?'<span class="rounded-full bg-[#C6F24E] px-2 py-1 text-xs">Faculty</span>':''}</strong><span class="text-xs text-[#121017]/45">${date(p.created_at)}</span></div><p class="mt-3 whitespace-pre-wrap text-sm">${esc(p.content)}</p>${p.event_title?`<p class="mt-2 text-xs text-[#397565]">${esc(p.event_title)}</p>`:''}${p.image_path?`<img class="mt-3 max-h-96 w-full rounded-xl object-contain" src="${esc(p.image_path)}" alt="Post image">`:''}${p.user_id==data.user_id?`<div class="mt-3 flex gap-3"><button class="text-sm font-bold text-[#397565]" data-edit="${p.id}">Edit</button><button class="text-sm font-bold text-red-600" data-delete="${p.id}">Delete</button></div>`:''}`)).join('') || empty('No posts to show.')}</div>`;
      host.querySelector('[data-post-form]').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);fd.set('action','create');await save(fd);};
      host.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{past=b.dataset.filter==='past';render();});
      host.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this post?'))return;const fd=new FormData();fd.set('action','delete');fd.set('id',b.dataset.delete);await save(fd);});
      host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const p=data.posts.find(x=>x.id==b.dataset.edit), form=host.querySelector('[data-post-form]');form.elements.content.value=p.content;form.elements.event_id.value=p.event_id||'';form.dataset.edit=p.id;form.querySelector('button').textContent='Save changes';form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form);fd.set('action','update');fd.set('id',p.id);await save(fd);};form.scrollIntoView({behavior:'smooth'});});
    };
    const save=async fd=>{try{await axios.post('api/faculty.php?page=posts',fd,{headers:{'X-CSRF-Token':csrf}});const updated=await get();Object.assign(data,updated);render();}catch(e){alert(e.response?.data?.message||'Post could not be saved.');}};render();
  }

  async function profile() {
    const data=await get();
    host.innerHTML=card(`<form class="grid gap-4 sm:grid-cols-2" data-profile>${[['first_name','First name'],['middle_name','Middle name'],['last_name','Last name'],['email','Email']].map(([key,label])=>`<label class="grid gap-1 text-sm font-bold">${label}<input class="min-h-11 rounded-xl border px-3 font-normal" name="${key}" value="${esc(data[key]||'')}" ${key==='email'?'type="email"':''} ${key==='first_name'||key==='last_name'?'required':''}></label>`).join('')}<label class="grid gap-1 text-sm font-bold sm:col-span-2">Bio<textarea class="min-h-28 rounded-xl border p-3 font-normal" name="bio" maxlength="280">${esc(data.bio||'')}</textarea></label><label class="grid gap-1 text-sm font-bold">Profile picture<input type="file" name="photo" accept="image/jpeg,image/png,image/webp"></label>${data.profile_photo_path?`<img class="h-24 w-24 rounded-full object-cover" src="${esc(data.profile_photo_path)}" alt="Profile picture">`:''}<div class="sm:col-span-2"><button class="rounded-xl bg-[#397565] px-5 py-3 text-sm font-bold text-white">Save profile</button><p class="mt-2 text-xs text-[#121017]/50">Role and assigned team are managed by the SBO Adviser.</p></div></form>`);
    host.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await axios.post('api/faculty.php?page=profile',new FormData(e.target),{headers:{'X-CSRF-Token':csrf}});alert('Profile updated.');location.reload();}catch(error){alert(error.response?.data?.message||'Profile could not be saved.');}};
  }

  window.SharedNavigation.ready.then(async session=>{csrf=session.csrfToken;await ({students,leaderboard,team,attendance,posts,profile})[page]();}).catch(error=>{console.error(error);host.textContent=error.response?.data?.message||'This page could not be loaded.';});
})();
