(() => {
  'use strict';
  const page = document.body.dataset.facultyPage;
  const host = document.querySelector('[data-faculty-content]');
  const esc = value => window.SharedNavigation.escapeHtml(value);
  const card = (body, extra='') => `<section class="rounded-3xl border border-[#397565]/15 bg-white p-5 shadow-sm sm:p-6 ${extra}">${body}</section>`;
  const empty = message => card(`<p class="py-10 text-center text-sm text-[#121017]/55">${esc(message)}</p>`);
  const date = value => value ? new Date(value.replace(' ','T')).toLocaleString('en-PH',{dateStyle:'medium',timeStyle:'short'}) : '—';
  const status = value => `<span class="rounded-full bg-[#397565]/10 px-2 py-1 text-xs font-bold text-[#397565]">${esc(value || 'Unrecorded')}</span>`;
  const get = async (name=page, params={}) => (await axios.get('api/faculty.php',{params:{page:name,...params}})).data.data;
  let csrf = '';

  async function students() {
    const first=await get('students',{page_number:1});
    if (!first.team) { host.innerHTML=empty('No team is assigned to your Faculty account. Contact the SBO Adviser.'); return; }
    host.innerHTML=card(`<div class="flex flex-wrap gap-3"><input class="min-h-11 min-w-[220px] flex-1 rounded-xl border px-3" placeholder="Search name or Student ID" data-search aria-label="Search students"><select class="min-h-11 rounded-xl border px-3" data-event aria-label="Filter event"><option value="">All events</option>${Object.entries(first.events).map(([id,title])=>`<option value="${id}">${esc(title)}</option>`).join('')}</select><select class="min-h-11 rounded-xl border px-3" data-status aria-label="Filter attendance status"><option value="">All statuses</option>${['present','late','absent','excused','unrecorded'].map(s=>`<option value="${s}">${s}</option>`).join('')}</select></div><p class="mt-3 text-xs text-[#121017]/50">${esc(first.team.name)} · View only · Attendance loads when a student is opened</p><div class="mt-5 grid gap-3" data-list></div><div class="mt-4 hidden flex-wrap items-center justify-between gap-3 border-t border-[#121017]/10 pt-4 text-xs text-[#121017]/50" data-pagination></div>`);
    const search=host.querySelector('[data-search]'),eventFilter=host.querySelector('[data-event]'),statusFilter=host.querySelector('[data-status]'),list=host.querySelector('[data-list]'),pager=host.querySelector('[data-pagination]');
    let currentPage=1,request=0,searchTimer;
    const historyRecord=a=>`<div class="rounded-xl bg-[#F7F4ED] p-3 text-sm"><strong>${esc(a.event_title)}</strong> · ${esc(a.date)} ${status(a.status)}${a.manual_status?'<span class="ml-2 text-[9px] font-black uppercase text-[#b94312]">Adviser corrected</span>':''}<p class="mt-2 text-xs text-[#121017]/55">Morning: ${esc(a.morning_in_at||'—')} – ${esc(a.morning_out_at||'—')} · Afternoon: ${esc(a.afternoon_in_at||'—')} – ${esc(a.afternoon_out_at||'—')}</p></div>`;
    const loadHistory=async(details,studentId,pageNumber=1)=>{
      const target=details.querySelector('[data-history]');target.innerHTML='<p class="text-sm text-[#121017]/50">Loading attendance…</p>';
      try{
        const data=await get('student_history',{student_id:studentId,event_id:eventFilter.value,page_number:pageNumber});
        target.innerHTML=data.records.length?data.records.map(historyRecord).join(''):'<p class="text-sm text-[#121017]/50">No attendance recorded.</p>';
        if(data.pagination.last_page>1){const controls=document.createElement('div');controls.className='flex items-center justify-between pt-2 text-xs text-[#121017]/50';controls.innerHTML=`<span>History page ${data.pagination.current_page} of ${data.pagination.last_page}</span><span class="flex gap-2"><button class="rounded-lg border px-3 py-2 font-bold disabled:opacity-30" type="button" data-history-page="${data.pagination.current_page-1}" ${data.pagination.current_page===1?'disabled':''}>Previous</button><button class="rounded-lg border px-3 py-2 font-bold disabled:opacity-30" type="button" data-history-page="${data.pagination.current_page+1}" ${data.pagination.current_page===data.pagination.last_page?'disabled':''}>Next</button></span>`;controls.querySelectorAll('[data-history-page]').forEach(button=>button.onclick=()=>loadHistory(details,studentId,Number(button.dataset.historyPage)));target.append(controls);}
      }catch(error){target.innerHTML=`<p class="text-sm font-bold text-[#b94312]">${esc(error.response?.data?.message||'Attendance history could not be loaded.')}</p>`;}
    };
    const renderPager=pageData=>{
      const visible=pageData.total>0;pager.classList.toggle('hidden',!visible);pager.classList.toggle('flex',visible);pager.replaceChildren();if(!visible)return;
      const count=document.createElement('span');count.textContent=`Showing ${pageData.from.toLocaleString()}–${pageData.to.toLocaleString()} of ${pageData.total.toLocaleString()} students`;
      const controls=document.createElement('span');controls.className='flex items-center gap-2';const position=document.createElement('span');position.textContent=`${pageData.current_page} / ${pageData.last_page}`;
      const button=(label,target,disabled)=>{const control=document.createElement('button');control.type='button';control.className='rounded-lg border px-3 py-2 font-bold disabled:opacity-30';control.textContent=label;control.disabled=disabled;control.onclick=()=>load(target);return control;};
      controls.append(button('Previous',pageData.current_page-1,pageData.current_page===1),position,button('Next',pageData.current_page+1,pageData.current_page===pageData.last_page));pager.append(count,controls);
    };
    const render=data=>{
      list.innerHTML=data.students.length?data.students.map(student=>`<details class="rounded-2xl border border-[#121017]/10 p-4" data-student-id="${student.id}"><summary class="cursor-pointer font-bold">${esc(student.name)} <span class="ml-2 text-xs font-normal text-[#121017]/50">${esc(student.id_number)} · ${esc(student.year_level||'Year not set')} · ${esc(student.team)} · ${student.attendance_count} attendance records</span></summary><div class="mt-3 grid gap-2" data-history><p class="text-sm text-[#121017]/50">Open to load attendance history.</p></div></details>`).join(''):'<p class="py-8 text-center text-sm text-[#121017]/50">No matching students.</p>';
      list.querySelectorAll('details').forEach(details=>details.addEventListener('toggle',()=>{if(details.open&&!details.dataset.loaded){details.dataset.loaded='true';loadHistory(details,Number(details.dataset.studentId));}}));renderPager(data.pagination);
    };
    const load=async(targetPage=1)=>{const serial=++request;const data=await get('students',{search:search.value.trim(),event_id:eventFilter.value,status:statusFilter.value,page_number:targetPage});if(serial!==request)return;currentPage=data.pagination.current_page;render(data);};
    search.oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>load(1),300);};eventFilter.onchange=()=>load(1);statusFilter.onchange=()=>load(1);currentPage=first.pagination.current_page;render(first);
  }

  async function leaderboard() {
    const first=await get(); let selected=first.events.find(e=>new Date(e.end_at.replace(' ','T'))>=new Date())?.id || first.events[0]?.id || null;
    let category=''; let past=false;
    const render=async()=>{
      const data=await get('leaderboard',selected?{event_id:selected,...(category?{category_id:category}:{})}:{});
      const now=new Date(); const active=first.events.filter(e=>new Date(e.end_at.replace(' ','T'))>=now), old=first.events.filter(e=>new Date(e.end_at.replace(' ','T'))<now);
      host.innerHTML=`<div class="flex flex-wrap gap-2">${active.map(e=>`<button class="rounded-xl px-4 py-2 text-sm font-bold ${selected==e.id?'bg-[#397565] text-white':'bg-white text-[#397565]'}" data-event="${e.id}">${esc(e.title)}</button>`).join('')}<button class="rounded-xl px-4 py-2 text-sm font-bold ${past?'bg-[#397565] text-white':'bg-white text-[#397565]'}" data-past>Past Events</button></div>${past?`<div class="mt-3 flex flex-wrap gap-2">${old.map(e=>`<button class="rounded-xl border px-3 py-2 text-xs font-bold ${selected==e.id?'border-[#397565] text-[#397565]':''}" data-event="${e.id}">${esc(e.title)}</button>`).join('') || '<p class="text-sm">No past events.</p>'}</div>`:''}<div class="mt-5"><label class="text-sm font-bold">Category <select class="ml-2 min-h-11 rounded-xl border bg-white px-3" data-category><option value="">All categories</option>${data.categories.map(c=>`<option value="${c.id}" ${category==c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label></div><div class="mt-5 grid gap-3">${data.rankings.length?data.rankings.map(t=>card(`<div class="flex items-center justify-between gap-3"><div><span class="text-xs font-bold text-[#397565]">#${t.rank || '—'}</span><h2 class="font-black">${esc(t.name)} ${t.id===data.team_id?'<span class="rounded-full bg-[#C6F24E] px-2 py-1 text-xs">Your team</span>':''}</h2></div><strong class="text-xl">${t.total_score} pts</strong></div>`,t.id===data.team_id?'ring-2 ring-[#397565]':'')).join(''):empty('No scores are available for this event and category.')}</div>`;
      host.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.event);category='';render();});
      host.querySelector('[data-past]').onclick=()=>{past=!past;render();};
      host.querySelector('[data-category]').onchange=e=>{category=e.target.value;render();};
    }; await render();
  }

  async function team() {
    const {team:t}=await get();
    if (!t) {host.innerHTML=empty('No team is assigned to your Faculty account. Contact the SBO Adviser.');return;}
    host.innerHTML=`<div class="grid gap-4 md:grid-cols-3">${card(`<p class="text-xs uppercase text-[#397565]">Assigned team</p><h2 class="mt-2 text-2xl font-black">${esc(t.name)}</h2><p class="text-sm">${esc(t.school_year)}</p>`)}${card(`<p class="text-xs uppercase text-[#397565]">Current rank</p><strong class="text-3xl">${t.rank?'#'+t.rank:'Unranked'}</strong>`)}${card(`<p class="text-xs uppercase text-[#397565]">Members</p><strong class="text-3xl">${t.members_count}</strong>`)}</div><div class="mt-4 grid gap-4 md:grid-cols-2">${card(`<div class="flex items-center justify-between gap-3"><h2 class="font-black">Member preview</h2><a class="text-xs font-bold text-[#397565]" href="pages/faculty/students.html">View all ${t.members_count}</a></div><ul class="mt-3 space-y-2 text-sm">${t.member_preview.map(m=>`<li>${esc(m.name)} · ${esc(m.id_number)}</li>`).join('') || '<li>No members yet.</li>'}</ul>`)}${card(`<h2 class="font-black">Scores</h2><ul class="mt-3 space-y-2 text-sm">${t.scores.map(s=>`<li>${esc(s.event_title)} · ${esc(s.category)}: <strong>${s.points} pts</strong></li>`).join('') || '<li>No scores yet.</li>'}</ul>`)}${card(`<h2 class="font-black">Attendance summary</h2><ul class="mt-3 space-y-2 text-sm">${t.attendance.map(a=>`<li>${esc(a.status)}: ${a.total}</li>`).join('') || '<li>No attendance yet.</li>'}</ul>`)}${card(`<h2 class="font-black">Upcoming activities</h2><ul class="mt-3 space-y-2 text-sm">${t.activities.map(a=>`<li>${esc(a.title)} · ${date(a.start_at)}</li>`).join('') || '<li>No upcoming activities.</li>'}</ul>`)}${card(`<h2 class="font-black">Announcements</h2><ul class="mt-3 space-y-3 text-sm">${t.announcements.map(a=>`<li>${esc(a.content)} <span class="text-xs text-[#121017]/45">${date(a.created_at)}</span></li>`).join('') || '<li>No announcements.</li>'}</ul>`,'md:col-span-2')}</div>`;
  }

  async function attendance() {
    const data=await get();
    if(!data.team){host.innerHTML=empty('No team is assigned to your Faculty account. Contact the SBO Adviser before scanning attendance.');return;}
    host.innerHTML=card(`<h2 class="font-black">Scan student attendance</h2><p class="mt-1 text-sm text-[#121017]/55">Only Student QR codes from ${esc(data.team.name)} can be recorded. Choose the event session and Time In or Time Out.</p><label class="mt-4 grid gap-1 text-sm font-bold">Event session<select class="min-h-11 rounded-xl border bg-white px-3" data-scan-session></select></label><div class="mt-4 flex gap-2"><button class="min-h-11 rounded-xl border px-4 text-sm font-bold" type="button" data-phase="in">Time In</button><button class="min-h-11 rounded-xl border px-4 text-sm font-bold" type="button" data-phase="out">Time Out</button></div><p class="mt-3 text-sm text-[#121017]/55" data-scan-window></p><button class="mt-4 min-h-11 rounded-xl bg-[#397565] px-5 text-sm font-bold text-white disabled:opacity-40" type="button" data-camera-button>Open QR scanner</button><div class="mt-4 hidden max-w-lg overflow-hidden rounded-xl bg-[#121017]" data-camera-panel><video class="aspect-square w-full object-cover" playsinline muted data-camera-video></video></div><p class="mt-3 text-sm" data-scan-message aria-live="polite">Ready to scan.</p>`)+card('<h2 class="font-black">Your team scans</h2><div class="mt-3 grid gap-2" data-scan-history></div>','mt-4');
    let sessions=data.sessions||[],phase='in',scanner=null,qrModule=null,working=false,lastToken='',lastAt=0;
    const select=host.querySelector('[data-scan-session]'),video=host.querySelector('[data-camera-video]'),cameraButton=host.querySelector('[data-camera-button]'),panel=host.querySelector('[data-camera-panel]'),message=host.querySelector('[data-scan-message]');
    const selected=()=>sessions.find(s=>`${s.event_schedule_id}:${s.session_code}`===select.value);
    const history=records=>{host.querySelector('[data-scan-history]').innerHTML=records.length?records.map(r=>`<div class="rounded-xl border border-[#121017]/10 p-3 text-sm"><strong>${esc(r.student_name)}</strong> · ${esc(r.id_number)}<p class="mt-1 text-xs text-[#121017]/55">${esc(r.event_title)} · ${esc(r.phase==='out'?'Time Out':'Time In')} · ${date(r.scanned_at)}</p></div>`).join(''):'<p class="text-sm text-[#121017]/50">No students scanned yet.</p>';};
    const stop=()=>{if(scanner){scanner.destroy();scanner=null;}panel.classList.add('hidden');cameraButton.textContent='Open QR scanner';};
    const controls=()=>{const s=selected();host.querySelectorAll('[data-phase]').forEach(b=>{const active=b.dataset.phase===phase;b.classList.toggle('bg-[#397565]',active);b.classList.toggle('text-white',active);b.classList.toggle('bg-white',!active);});const open=Boolean(s?.[`${phase}_window_open`]);cameraButton.disabled=!open;host.querySelector('[data-scan-window]').textContent=!s?'No attendance session is enabled for your team today.':open?`Time ${phase==='in'?'In':'Out'} scanning is open for ${s.event_name}.`:`Time ${phase==='in'?'In':'Out'} scanning is closed for ${s.event_name}.`;if(!open)stop();};
    const refresh=async()=>{const updated=await get('attendance');sessions=updated.sessions||[];const value=select.value;select.innerHTML=sessions.map(s=>`<option value="${s.event_schedule_id}:${s.session_code}">${esc(s.event_name)} · ${esc(s.session_name)}</option>`).join('');if(sessions.some(s=>`${s.event_schedule_id}:${s.session_code}`===value))select.value=value;history(updated.records||[]);controls();};
    const location=()=>new Promise(resolve=>{if(!navigator.geolocation){resolve({unavailable_reason:'geolocation_unavailable'});return;}navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_m:p.coords.accuracy,timestamp_ms:p.timestamp}),e=>resolve({unavailable_reason:e.code===1?'permission_denied':e.code===3?'location_timeout':'location_unavailable'}),{enableHighAccuracy:true,maximumAge:5000,timeout:8000});});
    const scan=async result=>{const token=String(result?.data||'').trim(),s=selected();if(!token||!s||working||!s[`${phase}_window_open`]||(token===lastToken&&Date.now()-lastAt<30000))return;working=true;lastToken=token;lastAt=Date.now();message.textContent='Checking location and recording attendance…';try{const response=await axios.post('api/faculty.php?page=scan',{schedule_id:s.event_schedule_id,session:s.session_code,checkpoint:phase,mode:'qr',token,location:await location()},{headers:{'X-CSRF-Token':csrf}});const student=response.data.data.student;message.textContent=`${phase==='in'?'Time In':'Time Out'} recorded for ${student.full_name} (${student.id_number}).`;message.className='mt-3 text-sm font-bold text-[#397565]';await refresh();}catch(e){message.textContent=e.response?.data?.message||'Attendance scan failed.';message.className='mt-3 text-sm font-bold text-[#D64A12]';lastAt=Date.now()-29000;}finally{working=false;}};
    cameraButton.onclick=async()=>{if(scanner){stop();return;}if(!window.isSecureContext){message.textContent='Camera scanning requires HTTPS or localhost.';return;}try{qrModule??=(await import(new URL('js/vendor/qr-scanner/qr-scanner.min.js',document.baseURI))).default;scanner=new qrModule(video,scan,{preferredCamera:'environment',maxScansPerSecond:10,highlightScanRegion:true,highlightCodeOutline:true,returnDetailedScanResult:true});panel.classList.remove('hidden');await scanner.start();cameraButton.textContent='Close scanner';message.textContent='Point the camera at a student QR code.';}catch(e){stop();message.textContent=e?.message||'Camera is unavailable. Check permission and retry.';}};
    host.querySelectorAll('[data-phase]').forEach(b=>b.onclick=()=>{phase=b.dataset.phase;controls();});select.onchange=()=>{stop();controls();};history(data.records||[]);if(sessions.some(s=>s.in_window_open))phase='in';else if(sessions.some(s=>s.out_window_open))phase='out';select.innerHTML=sessions.map(s=>`<option value="${s.event_schedule_id}:${s.session_code}">${esc(s.event_name)} · ${esc(s.session_name)}</option>`).join('');controls();
    const timer=setInterval(()=>{if(!document.hidden&&!working)refresh().catch(()=>{});},30000);window.addEventListener('pagehide',()=>{clearInterval(timer);stop();},{once:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
  }

  async function profile() {
    const data=await get();
    host.innerHTML=card(`<form class="grid gap-4 sm:grid-cols-2" data-profile>${[['first_name','First name'],['middle_name','Middle name'],['last_name','Last name'],['email','Email']].map(([key,label])=>`<label class="grid gap-1 text-sm font-bold">${label}<input class="min-h-11 rounded-xl border px-3 font-normal" name="${key}" value="${esc(data[key]||'')}" ${key==='email'?'type="email"':''} ${key==='first_name'||key==='last_name'?'required':''}></label>`).join('')}<label class="grid gap-1 text-sm font-bold sm:col-span-2">Bio<textarea class="min-h-28 rounded-xl border p-3 font-normal" name="bio" maxlength="280">${esc(data.bio||'')}</textarea></label><label class="grid gap-1 text-sm font-bold">Profile picture<input type="file" name="photo" accept="image/jpeg,image/png,image/webp"></label>${data.profile_photo_path?`<img class="h-24 w-24 rounded-full object-cover" src="${esc(data.profile_photo_path)}" alt="Profile picture">`:''}<div class="sm:col-span-2"><button class="rounded-xl bg-[#397565] px-5 py-3 text-sm font-bold text-white">Save profile</button><p class="mt-2 text-xs text-[#121017]/50">Role and assigned team are managed by the SBO Adviser.</p></div></form>`);
    host.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await axios.post('api/faculty.php?page=profile',new FormData(e.target),{headers:{'X-CSRF-Token':csrf}});alert('Profile updated.');location.reload();}catch(error){alert(error.response?.data?.message||'Profile could not be saved.');}};
  }

  window.SharedNavigation.ready.then(async session=>{csrf=session.csrfToken;await ({students,leaderboard,team,attendance,profile})[page]();}).catch(error=>{console.error(error);host.textContent=error.response?.data?.message||'This page could not be loaded.';});
})();
