<?php
declare(strict_types=1);
require_once __DIR__.'/db_connect.php';require_once __DIR__.'/ApiSupport.php';require_once __DIR__.'/SboAuthorization.php';
final class SboScoresRepository{
 public function __construct(private readonly PDO $db,private readonly SboAuthorization $auth){}
 public function show(int $user,int $id):array{$assignments=$this->auth->assignments($user,'scoring');$selected=null;foreach($assignments as $row)if($row['id']===$id)$selected=$row;if(!$selected&&$assignments)$selected=$assignments[0];if(!$selected)return compact('assignments','selected')+['categories'=>[],'teams'=>[],'scores'=>[],'sheet'=>null];
  $c=$this->db->prepare('SELECT id,name,min_points,max_points,sort_order FROM tbl_score_categories WHERE event_id=? AND activity_id=? ORDER BY sort_order,id');$c->execute([$selected['event_id'],$selected['activity_id']]);$categories=$c->fetchAll();foreach($categories as &$v){$v['id']=(int)$v['id'];$v['min_points']=(float)$v['min_points'];$v['max_points']=(float)$v['max_points'];}unset($v);
  $t=$this->db->prepare("SELECT DISTINCT t.id,t.name,t.color FROM tbl_teams t LEFT JOIN tbl_event_team et ON et.team_id=t.id AND et.event_id=? WHERE t.is_active=1 AND (et.id IS NOT NULL OR NOT EXISTS(SELECT 1 FROM tbl_event_team x WHERE x.event_id=?)) ORDER BY t.name");$t->execute([$selected['event_id'],$selected['event_id']]);$teams=$t->fetchAll();foreach($teams as &$v)$v['id']=(int)$v['id'];unset($v);
  $s=$this->db->prepare('SELECT team_id,score_category_id,points FROM tbl_scores WHERE event_id=? AND score_category_id IN(SELECT id FROM tbl_score_categories WHERE activity_id=?)');$s->execute([$selected['event_id'],$selected['activity_id']]);$scores=[];foreach($s as $v)$scores[$v['team_id']][$v['score_category_id']]=(float)$v['points'];$q=$this->db->prepare('SELECT * FROM tbl_score_sheets WHERE event_id=? AND activity_id=?');$q->execute([$selected['event_id'],$selected['activity_id']]);$sheet=$q->fetch()?:null;return compact('assignments','selected','categories','teams','scores','sheet');}
 public function save(int $user,array $input):string{$assignment=$this->auth->assignment($user,(int)($input['assignment_id']??0),'scoring');$finalize=!empty($input['finalize']);$rows=$input['scores']??null;if(!is_array($rows))throw new InvalidArgumentException('Score entries are required.');$sheet=$this->row('SELECT * FROM tbl_score_sheets WHERE event_id=? AND activity_id=?',[$assignment['event_id'],$assignment['activity_id']]);if($sheet&&$sheet['status']==='finalized')throw new InvalidArgumentException('This score sheet is finalized. Ask the adviser to reopen it.');$categories=$this->map('SELECT id,min_points,max_points FROM tbl_score_categories WHERE event_id=? AND activity_id=?',[$assignment['event_id'],$assignment['activity_id']]);$teams=$this->map('SELECT id FROM tbl_teams WHERE is_active=1');if(!$categories)throw new InvalidArgumentException('The adviser has not created scoring criteria for this activity.');
  foreach($rows as $team=>$values){if(!isset($teams[(int)$team])||!is_array($values))throw new InvalidArgumentException('Invalid participating team.');foreach($values as $category=>$points){$category=(int)$category;if(!isset($categories[$category])||!is_numeric($points))throw new InvalidArgumentException('Every submitted score must be numeric.');if((float)$points<(float)$categories[$category]['min_points']||(float)$points>(float)$categories[$category]['max_points'])throw new InvalidArgumentException('A score is outside its allowed minimum or maximum.');}}
  $this->db->beginTransaction();try{$up=$this->db->prepare('INSERT INTO tbl_scores(event_id,team_id,score_category_id,points,recorded_by,created_at,updated_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON DUPLICATE KEY UPDATE points=VALUES(points),recorded_by=VALUES(recorded_by),updated_at=CURRENT_TIMESTAMP');foreach($rows as $team=>$values)foreach($values as $category=>$points)$up->execute([$assignment['event_id'],(int)$team,(int)$category,(float)$points,$user]);if(!$sheet){$this->db->prepare("INSERT INTO tbl_score_sheets(event_id,activity_id,sbo_event_assignment_id,status,submitted_by,finalized_at,created_at,updated_at) VALUES(?,?,?,? ,?,IF(?='finalized',CURRENT_TIMESTAMP,NULL),CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)")->execute([$assignment['event_id'],$assignment['activity_id'],$assignment['id'],$finalize?'finalized':'draft',$user,$finalize?'finalized':'draft']);}else{$this->db->prepare("UPDATE tbl_score_sheets SET status=?,submitted_by=?,finalized_at=IF(?='finalized',CURRENT_TIMESTAMP,NULL),updated_at=CURRENT_TIMESTAMP WHERE id=?")->execute([$finalize?'finalized':'draft',$user,$finalize?'finalized':'draft',$sheet['id']]);}$this->db->commit();return$finalize?'Scores finalized successfully.':'Score draft saved.';}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
 private function row(string $q,array$p=[]):array|false{$s=$this->db->prepare($q);$s->execute($p);return$s->fetch();}private function map(string$q,array$p=[]):array{$s=$this->db->prepare($q);$s->execute($p);$out=[];foreach($s as$r)$out[(int)$r['id']]=$r;return$out;}
}
$actor=AuthGuard::requireRole('SBO Officer');$db=(new Database())->connection();$repo=new SboScoresRepository($db,new SboAuthorization($db));try{if($_SERVER['REQUEST_METHOD']==='GET')JsonResponse::send(['success'=>true,'data'=>$repo->show((int)$actor['id'],(int)($_GET['assignment_id']??0))]);if($_SERVER['REQUEST_METHOD']!=='POST')JsonResponse::send(['success'=>false,'message'=>'Method not allowed.'],405);if(!SessionManager::validateCsrf($_SERVER['HTTP_X_CSRF_TOKEN']??null))JsonResponse::send(['success'=>false,'message'=>'Your session expired.'],403);$in=json_decode(file_get_contents('php://input'),true);JsonResponse::send(['success'=>true,'message'=>$repo->save((int)$actor['id'],is_array($in)?$in:[])]);}catch(DomainException$e){JsonResponse::send(['success'=>false,'message'=>$e->getMessage()],403);}catch(Throwable$e){error_log($e->getMessage());JsonResponse::send(['success'=>false,'message'=>$e instanceof InvalidArgumentException?$e->getMessage():'Unable to save scores.'],422);}
