<?php
declare(strict_types=1);
require_once __DIR__.'/db_connect.php';require_once __DIR__.'/ApiSupport.php';require_once __DIR__.'/SboAuthorization.php';
final class SboMediaRepository{
 public function __construct(private readonly PDO$db,private readonly SboAuthorization$auth){}
 public function index(int$user,int$id):array{$assignments=$this->auth->assignments($user,'media');$selected=null;foreach($assignments as$row)if($row['id']===$id)$selected=$row;if(!$selected&&$assignments)$selected=$assignments[0];$posts=[];if($selected){$s=$this->db->prepare('SELECT id,content,image_path,status,rejection_reason,created_at,updated_at FROM tbl_posts WHERE user_id=? AND sbo_event_assignment_id=? AND deleted_at IS NULL ORDER BY created_at DESC');$s->execute([$user,$selected['id']]);$posts=$s->fetchAll();foreach($posts as &$p)$p['id']=(int)$p['id'];unset($p);}return compact('assignments','selected','posts');}
 public function create(int$user,array$in,array$files):string{$a=$this->auth->assignment($user,(int)($in['assignment_id']??0),'media');$content=$this->content($in);$path=$this->upload($files['image']??null);$this->db->beginTransaction();try{$s=$this->db->prepare("INSERT INTO tbl_posts(user_id,event_id,activity_id,sbo_event_assignment_id,category,content,image_path,status,is_official,created_at,updated_at) VALUES(?,?,?,?, 'event-media',?,?,'pending',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");$s->execute([$user,$a['event_id'],$a['activity_id'],$a['id'],$content,$path]);$id=(int)$this->db->lastInsertId();$this->db->prepare("INSERT INTO tbl_post_audits(post_id,actor_id,action,from_status,to_status,created_at,updated_at) VALUES(?,?,'submitted',NULL,'pending',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)")->execute([$id,$user]);$this->db->commit();return'Event post submitted for adviser review.';}catch(Throwable$e){if($this->db->inTransaction())$this->db->rollBack();if($path)$this->remove($path);throw$e;}}
 public function update(int$user,array$in,array$files):string{$id=(int)($in['id']??0);$post=$this->post($id,$user);$content=$this->content($in);$new=$this->upload($files['image']??null);$path=$new?:$post['image_path'];$this->db->prepare("UPDATE tbl_posts SET content=?,image_path=?,status='pending',rejection_reason=NULL,reviewed_by=NULL,reviewed_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?")->execute([$content,$path,$id,$user]);if($new&&$post['image_path'])$this->remove($post['image_path']);return'Event post updated and resubmitted.';}
 public function delete(int$user,int$id):string{$post=$this->post($id,$user);$this->db->prepare('UPDATE tbl_posts SET deleted_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?')->execute([$id,$user]);return'Event post deleted.';}
 private function post(int$id,int$user):array{$s=$this->db->prepare('SELECT * FROM tbl_posts WHERE id=? AND user_id=? AND deleted_at IS NULL');$s->execute([$id,$user]);$p=$s->fetch();if(!$p)throw new InvalidArgumentException('Post not found or not owned by you.');return$p;}
 private function content(array$in):string{$v=trim((string)($in['content']??''));if($v===''||mb_strlen($v)>3000)throw new InvalidArgumentException('Caption is required and may not exceed 3,000 characters.');return$v;}
 private function upload(?array$file):?string{if(!$file||($file['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)return null;if(($file['error']??1)!==UPLOAD_ERR_OK||($file['size']??0)>8*1024*1024)throw new InvalidArgumentException('Photo upload failed or exceeds 8 MB.');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);$ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'][$mime]??null;if(!$ext)throw new InvalidArgumentException('Use a JPG, PNG, or WebP photo.');$dir=dirname(__DIR__).'/assets/uploads/posts';if(!is_dir($dir)&&!mkdir($dir,0775,true)&&!is_dir($dir))throw new RuntimeException('Upload directory could not be created.');$name=bin2hex(random_bytes(20)).'.'.$ext;if(!move_uploaded_file($file['tmp_name'],$dir.'/'.$name))throw new RuntimeException('Photo could not be stored.');return'assets/uploads/posts/'.$name;}
 private function remove(string$path):void{$root=realpath(dirname(__DIR__).'/assets/uploads/posts');$file=realpath(dirname(__DIR__).'/'.$path);if($root&&$file&&str_starts_with($file,$root.DIRECTORY_SEPARATOR))@unlink($file);}
}
$actor=AuthGuard::requireRole('SBO Officer');$db=(new Database())->connection();$repo=new SboMediaRepository($db,new SboAuthorization($db));try{if($_SERVER['REQUEST_METHOD']==='GET')JsonResponse::send(['success'=>true,'data'=>$repo->index((int)$actor['id'],(int)($_GET['assignment_id']??0))]);if($_SERVER['REQUEST_METHOD']!=='POST')JsonResponse::send(['success'=>false,'message'=>'Method not allowed.'],405);if(!SessionManager::validateCsrf($_SERVER['HTTP_X_CSRF_TOKEN']??null))JsonResponse::send(['success'=>false,'message'=>'Your session expired.'],403);$action=(string)($_POST['action']??'create');$message=match($action){'create'=>$repo->create((int)$actor['id'],$_POST,$_FILES),'update'=>$repo->update((int)$actor['id'],$_POST,$_FILES),'delete'=>$repo->delete((int)$actor['id'],(int)($_POST['id']??0)),default=>throw new InvalidArgumentException('Unknown media action.')};JsonResponse::send(['success'=>true,'message'=>$message]);}catch(DomainException$e){JsonResponse::send(['success'=>false,'message'=>$e->getMessage()],403);}catch(Throwable$e){error_log($e->getMessage());JsonResponse::send(['success'=>false,'message'=>$e instanceof InvalidArgumentException?$e->getMessage():'Media request failed.'],422);}
